### ISSUE TITLE
Static changes not recognized with bootRun

### ISSUE THREAD

**Issue by ganeshkantu** [grails-guides/angular2-combined#3]
Client static changes are not reflected with bootRun. If I change to use ng build --watch, the bootRun just waits for client changes and doesn't progress past the webapp build.

What should I use for this?

**Comment by averchenkov-r-a** [comment]
@ganeshkantu I think you need to run `bootRun` with `buildClient` (script `ng build`) and after run new task `buildClientWatch` (script `ng build --watch`).

**Comment by ganeshkantu** [comment]
@averchenkov-r-a Yeah. That's what I have been doing. It is ugly, but works.
