### ISSUE TITLE
Angular 2/4 assets are not loaded after combining

### ISSUE THREAD

**Issue by sandeepvedavyas** [grails-guides/angular2-combined#5]
I have followed all the steps given in http://guides.grails.org/angular2-combined/guide/index.html
application loaded but assets which i have mentioned in angular.cli is not getting loaded. When I run independent applications with ./gradlew bootRun --parallel in the angular profile app of same code everything works fine.

**Comment by jameskleeh** [comment]
Look at the complete example

**Comment by sandeepvedavyas** [comment]
I have checked the complete example and verified files, everything is similar but still, am facing this issue. Not sure if this is because of ng build --prod or other

**Comment by niravassar** [comment]
we are creating a new guide based upon #9
