### ISSUE TITLE
Can you use PathLocationStrategy with combined project?

### ISSUE THREAD

**Issue by raydawg2000** [grails-guides/angular2-combined#7]
I only seem to be able to get a combined project working with the older style HashLocationStrategy?

Using PathLocationStrategy if i have an Angular route for "/dashboard" then it gives me a 404 error because there is no backend mapping for "/dashboard".  If i change to use HashLocationStrategy then it works no problem "#/dashboard"

One interesting thing is when using PathLocationStrategy the initial page load works.  So if I visit localhost:8080 my routing will redirect to localhost:8080/dashboard and this works.  

`const routes: Routes = [
  {
    path: '',
    redirectTo: 'dashboard',
    pathMatch: 'full'
  },
  {
    path: 'dashboard',
    component: DashboardComponent
  }
];`

But if i do a page reload then I get the 404 error.  I can only get my app back by going to the root localhost:8080 and having the routing redirect me to the correct URL.

On some level I understand that you by refreshing your trying to make a request to the grails backend for a URL that doesn't exist, it only exists in Angular.  I just don't know how to configure the app to be able to make that distinction.  I feel like in the URLMappings i can somehow section off a url prefix such as "/api" and all URL matching after that prefix goes the server and anything else maps to Angular, but I don't know if thats possible.

**Comment by raydawg2000** [comment]
I think i got it figured, but if you have any better suggestions I am listening

updated URLMapings

`
        delete "/api/$controller/$id(.$format)?"(action:"delete")
        get "/api/$controller(.$format)?"(action:"index")
        get "/api/$controller/$id(.$format)?"(action:"show")
        post "/api/$controller(.$format)?"(action:"save")
        put "/api/$controller/$id(.$format)?"(action:"update")
        patch "/api/$controller/$id(.$format)?"(action:"patch")
        
        "/"(redirect: "/app/")
        "/app/**"(uri: "/index.html")
`

updated my index.html 

`<base href="/app">`

So now as long as the URL is prefixed with `/app/` anything after that will map the a Angular route

**Comment by niravassar** [comment]
we are creating a new guide based upon #9
