### ISSUE TITLE
Rewrite guide to use multi-project, unified Gradle build approach

### ISSUE THREAD

**Issue by ZacharyKlein** [grails-guides/angular2-combined#9]
I recommend that we rewrite this guide to be consistent with our two SPA/combined guides (React and Vue). The basic idea is that, rather than merging the Angular and Grails apps into a single project structure, we preserve the multi-project structure and provide a simple Gradle build that merges the two apps prior to building the deployable artifact (JAR or WAR file). 

There are many advantages to the multi-project approach - ease of upgrading both subprojects, cleaner delineation of frontend vs backend, and minimizing the learning curve for developers who might be working on only the frontend (they won't need to figure out the Grails project structure to do their work).  The two projects can even live in the same repo without major issue. The main reason (at least that I can think of) to combine them at all is to support a single deployment pipeline/artifact, and we can support that via Gradle quite easily. 

I think we should be promoting the above approach rather than risk helping folks work themselves into a difficult situation down the road when they attempt to upgrade their Angular stack or Grails version. 

React Guide - https://guides.grails.org/react-combined/guide/index.html
Vue Guide - https://guides.grails.org/grails-vue-combined/guide/index.html

**Comment by ZacharyKlein** [comment]
cc @jameskleeh @niravassar @jeffbrown Any thoughts on this proposal?

**Comment by jameskleeh** [comment]
Fine with me

**Comment by niravassar** [comment]
I’ll do the guide

**Comment by niravassar** [comment]
complete in the PR grails 4
